<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: persistence.proto

namespace Test\Persistence\ProtoBuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Test\Metadata\Persistence;

/**
 * Generated from protobuf message <code>Test.Persistence.ProtoBuf.TestSnapshot</code>
 */
class TestSnapshot extends Message
{
    /**
     * Generated from protobuf field <code>string message = 1;</code>
     */
    protected $message = '';

    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     * }
     */
    public function __construct(array|null $data = null)
    {
        Persistence::initOnce();

        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     *
     * @return $this
     */
    public function setMessage(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->message = $var;

        return $this;
    }
}
