<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: event.proto

namespace Test\Persistence\ProtoBuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Test\Metadata\Event;

/**
 * Generated from protobuf message <code>protobuf.UserCreated</code>
 */
class UserCreated extends Message
{
    /**
     * Generated from protobuf field <code>string userName = 1;</code>
     */
    protected $userName = '';
    /**
     * Generated from protobuf field <code>string email = 2;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string userID = 3;</code>
     */
    protected $userID = '';

    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $userName
     *     @type string $email
     *     @type string $userID
     * }
     */
    public function __construct(array|null $data = null)
    {
        Event::initOnce();

        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string userName = 1;</code>
     */
    public function getUserName(): string
    {
        return $this->userName;
    }

    /**
     * Generated from protobuf field <code>string userName = 1;</code>
     *
     * @return $this
     */
    public function setUserName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->userName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 2;</code>
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 2;</code>
     *
     * @return $this
     */
    public function setEmail(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userID = 3;</code>
     */
    public function getUserID(): string
    {
        return $this->userID;
    }

    /**
     * Generated from protobuf field <code>string userID = 3;</code>
     *
     * @return $this
     */
    public function setUserID(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->userID = $var;

        return $this;
    }
}
