<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: actor.proto

namespace Phluxor\ActorSystem\ProtoBuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Phluxor\Metadata\ProtoBuf\Actor;

/**
 * Generated from protobuf message <code>actor.DeadLetterResponse</code>
 */
class DeadLetterResponse extends Message
{
    /**
     * Generated from protobuf field <code>.actor.Pid target = 1;</code>
     */
    protected $target = null;

    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\ActorSystem\ProtoBuf\Pid $target
     * }
     */
    public function __construct(array|null $data = null)
    {
        Actor::initOnce();

        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid target = 1;</code>
     */
    public function getTarget(): Pid|null
    {
        return $this->target;
    }

    public function hasTarget()
    {
        return isset($this->target);
    }

    public function clearTarget(): void
    {
        unset($this->target);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid target = 1;</code>
     *
     * @return $this
     */
    public function setTarget(Pid $var)
    {
        GPBUtil::checkMessage($var, Pid::class);
        $this->target = $var;

        return $this;
    }
}
