<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: actor.proto

namespace Phluxor\ActorSystem\ProtoBuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Phluxor\Metadata\ProtoBuf\Actor;

/**
 * Generated from protobuf message <code>actor.Pid</code>
 */
class Pid extends Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string id = 2;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>uint32 request_id = 3;</code>
     */
    protected $request_id = 0;

    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type string $id
     *     @type int $request_id
     * }
     */
    public function __construct(array|null $data = null)
    {
        Actor::initOnce();

        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    public function getAddress(): string
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     *
     * @return $this
     */
    public function setAddress(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     *
     * @return $this
     */
    public function setId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 request_id = 3;</code>
     */
    public function getRequestId(): int
    {
        return $this->request_id;
    }

    /**
     * Generated from protobuf field <code>uint32 request_id = 3;</code>
     *
     * @return $this
     */
    public function setRequestId(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->request_id = $var;

        return $this;
    }
}
