<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: actor.proto

namespace Phluxor\ActorSystem\ProtoBuf;

use Google\Protobuf\Internal\Message;
use Phluxor\Metadata\ProtoBuf\Actor;

/**
 * Generated from protobuf message <code>actor.Stop</code>
 */
class Stop extends Message
{
    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct(array|null $data = null)
    {
        Actor::initOnce();

        parent::__construct($data);
    }
}
