<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: actor.proto

namespace Phluxor\ActorSystem\ProtoBuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Phluxor\Metadata\ProtoBuf\Actor;

/**
 * Generated from protobuf message <code>actor.Terminated</code>
 */
class Terminated extends Message
{
    /**
     * Generated from protobuf field <code>.actor.Pid who = 1;</code>
     */
    protected $who = null;
    /**
     * Generated from protobuf field <code>.actor.TerminatedReason why = 2;</code>
     */
    protected $why = 0;

    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\ActorSystem\ProtoBuf\Pid $who
     *     @type int $why
     * }
     */
    public function __construct(array|null $data = null)
    {
        Actor::initOnce();

        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid who = 1;</code>
     */
    public function getWho(): Pid|null
    {
        return $this->who;
    }

    public function hasWho()
    {
        return isset($this->who);
    }

    public function clearWho(): void
    {
        unset($this->who);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid who = 1;</code>
     *
     * @return $this
     */
    public function setWho(Pid $var)
    {
        GPBUtil::checkMessage($var, Pid::class);
        $this->who = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.actor.TerminatedReason why = 2;</code>
     */
    public function getWhy(): int
    {
        return $this->why;
    }

    /**
     * Generated from protobuf field <code>.actor.TerminatedReason why = 2;</code>
     *
     * @return $this
     */
    public function setWhy(int $var)
    {
        GPBUtil::checkEnum($var, TerminatedReason::class);
        $this->why = $var;

        return $this;
    }
}
