<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: actor.proto

namespace Phluxor\ActorSystem\ProtoBuf;

use UnexpectedValueException;

use function constant;
use function defined;
use function sprintf;
use function strtoupper;

/**
 * Protobuf type <code>actor.TerminatedReason</code>
 */
class TerminatedReason
{
    /**
     * Generated from protobuf enum <code>Stopped = 0;</code>
     */
    public const int Stopped = 0;

    /**
     * Generated from protobuf enum <code>AddressTerminated = 1;</code>
     */
    public const int AddressTerminated = 1;

    /**
     * Generated from protobuf enum <code>NotFound = 2;</code>
     */
    public const int NotFound = 2;

    private static $valueToName = [
        self::Stopped => 'Stopped',
        self::AddressTerminated => 'AddressTerminated',
        self::NotFound => 'NotFound',
    ];

    public static function name($value)
    {
        if (! isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no name defined for value %s',
                self::class,
                $value,
            ));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . strtoupper($name);
        if (! defined($const)) {
            throw new UnexpectedValueException(sprintf(
                'Enum %s has no value defined for name %s',
                self::class,
                $name,
            ));
        }

        return constant($const);
    }
}
