<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: actor.proto

namespace Phluxor\ActorSystem\ProtoBuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Phluxor\Metadata\ProtoBuf\Actor;

/**
 * Generated from protobuf message <code>actor.Unwatch</code>
 */
class Unwatch extends Message
{
    /**
     * Generated from protobuf field <code>.actor.Pid watcher = 1;</code>
     */
    protected $watcher = null;

    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\ActorSystem\ProtoBuf\Pid $watcher
     * }
     */
    public function __construct(array|null $data = null)
    {
        Actor::initOnce();

        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid watcher = 1;</code>
     */
    public function getWatcher(): Pid|null
    {
        return $this->watcher;
    }

    public function hasWatcher()
    {
        return isset($this->watcher);
    }

    public function clearWatcher(): void
    {
        unset($this->watcher);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid watcher = 1;</code>
     *
     * @return $this
     */
    public function setWatcher(Pid $var)
    {
        GPBUtil::checkMessage($var, Pid::class);
        $this->watcher = $var;

        return $this;
    }
}
