<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: router.proto

namespace Phluxor\Router\ProtoBuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Phluxor\Router\Metadata\ProtoBuf\Router;

/**
 * Generated from protobuf message <code>router.AdjustPoolSize</code>
 */
class AdjustPoolSize extends Message
{
    /**
     * Generated from protobuf field <code>int32 change = 1;</code>
     */
    protected $change = 0;

    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $change
     * }
     */
    public function __construct(array|null $data = null)
    {
        Router::initOnce();

        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 change = 1;</code>
     */
    public function getChange(): int
    {
        return $this->change;
    }

    /**
     * Generated from protobuf field <code>int32 change = 1;</code>
     *
     * @return $this
     */
    public function setChange(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->change = $var;

        return $this;
    }
}
