<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: router.proto

namespace Phluxor\Router\ProtoBuf;

use Google\Protobuf\Internal\Message;
use Phluxor\Router\Metadata\ProtoBuf\Router;

/**
 * Generated from protobuf message <code>router.GetRoutees</code>
 */
class GetRoutees extends Message
{
    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct(array|null $data = null)
    {
        Router::initOnce();

        parent::__construct($data);
    }
}
