<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: router.proto

namespace Phluxor\Router\ProtoBuf;

use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Phluxor\ActorSystem\ProtoBuf\Pid;
use Phluxor\Router\Metadata\ProtoBuf\Router;

/**
 * Generated from protobuf message <code>router.RemoveRoutee</code>
 */
class RemoveRoutee extends Message
{
    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     */
    protected $pid = null;

    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Phluxor\ActorSystem\ProtoBuf\Pid $pid
     * }
     */
    public function __construct(array|null $data = null)
    {
        Router::initOnce();

        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     */
    public function getPid(): Pid|null
    {
        return $this->pid;
    }

    public function hasPid()
    {
        return isset($this->pid);
    }

    public function clearPid(): void
    {
        unset($this->pid);
    }

    /**
     * Generated from protobuf field <code>.actor.Pid pid = 1;</code>
     *
     * @return $this
     */
    public function setPid(Pid $var)
    {
        GPBUtil::checkMessage($var, Pid::class);
        $this->pid = $var;

        return $this;
    }
}
