<?php

declare(strict_types=1);

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: router.proto

namespace Phluxor\Router\ProtoBuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\RepeatedField;
use Phluxor\ActorSystem\ProtoBuf\Pid;
use Phluxor\Router\Metadata\ProtoBuf\Router;

/**
 * Generated from protobuf message <code>router.Routees</code>
 */
class Routees extends Message
{
    /**
     * Generated from protobuf field <code>repeated .actor.Pid pids = 1;</code>
     */
    private $pids;

    /**
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Phluxor\ActorSystem\ProtoBuf\Pid>|\Google\Protobuf\Internal\RepeatedField $pids
     * }
     */
    public function __construct(array|null $data = null)
    {
        Router::initOnce();

        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .actor.Pid pids = 1;</code>
     */
    public function getPids(): RepeatedField
    {
        return $this->pids;
    }

    /**
     * Generated from protobuf field <code>repeated .actor.Pid pids = 1;</code>
     *
     * @param array<Pid>|RepeatedField $var
     *
     * @return $this
     */
    public function setPids(array|RepeatedField $var)
    {
        $arr        = GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, Pid::class);
        $this->pids = $arr;

        return $this;
    }
}
